### ISSUE TITLE
There should be an option to turn off trailing slash for base route in router.py

### ISSUE THREAD

**Issue by he1dj** [vitaliypopel/django-routify#13]
Even if auto_trailing_slash=False, Router automatically adds a trailing slash at the end, so it's not possible to get rid of the trailing slash for the base route of the router.

For example:

`books_router = Router("/books", "books", auto_trailing_slash=False)`

if I go to http://localhost:8000/books, it will add / at the end, making it /books/, but the child route will not have the trailing slash if auto_trailing_slash=False and route itself does not have the trailing slash. So I will have a base route /books/, and a child route /books/uuid/slug, the child route doesn't have a trailing slash. My suggestion is to add an option that makes the base route /books also possible to be with no trailing slash.

I fixed it by changing line 31 in router.py:

`self.__prefix = prefix.rstrip('/').lstrip('/') # originally + '/'`

So, my routes in views.py look like this:

`@books_router.route("/<str:uuid>/<slug:slug>", name="book_view")`

I add the slash at the beginning, just like I would do in frameworks like NestJs. Sorry if this issue is not properly organized, I am not a professional and usually I don't open issues, but this project is really neat and I would like it to get better, as I like this approach used in other frameworks.

**Comment by vitaliypopel** [comment]
Thank you for writing :)

That's good issue to be honest. I will do it today.
As I got it right, I will just automatically add trailing slash for prefix if only it setted to True, unless if it is False I will don't touch it, so yea

Thanks for helping <3, follow update today

**Comment by vitaliypopel** [comment]
Hadn't too much time yesterday to test new version correctly, today I found that something wrong.. Fixing it and then close issue again

**Comment by vitaliypopel** [comment]
Tests passed, all good
